/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppScheduleRouteImport } from './routes/_app/schedule'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppGpaSimulatorRouteImport } from './routes/_app/gpa-simulator'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCoursePlannerRouteImport } from './routes/_app/course-planner'
import { Route as AppAiAdvisorRouteImport } from './routes/_app/ai-advisor'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppGpaSimulatorRoute = AppGpaSimulatorRouteImport.update({
  id: '/gpa-simulator',
  path: '/gpa-simulator',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursePlannerRoute = AppCoursePlannerRouteImport.update({
  id: '/course-planner',
  path: '/course-planner',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAdvisorRoute = AppAiAdvisorRouteImport.update({
  id: '/ai-advisor',
  path: '/ai-advisor',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-advisor': typeof AppAiAdvisorRoute
  '/course-planner': typeof AppCoursePlannerRoute
  '/dashboard': typeof AppDashboardRoute
  '/gpa-simulator': typeof AppGpaSimulatorRoute
  '/insights': typeof AppInsightsRoute
  '/schedule': typeof AppScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-advisor': typeof AppAiAdvisorRoute
  '/course-planner': typeof AppCoursePlannerRoute
  '/dashboard': typeof AppDashboardRoute
  '/gpa-simulator': typeof AppGpaSimulatorRoute
  '/insights': typeof AppInsightsRoute
  '/schedule': typeof AppScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/ai-advisor': typeof AppAiAdvisorRoute
  '/_app/course-planner': typeof AppCoursePlannerRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gpa-simulator': typeof AppGpaSimulatorRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/schedule': typeof AppScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-advisor'
    | '/course-planner'
    | '/dashboard'
    | '/gpa-simulator'
    | '/insights'
    | '/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-advisor'
    | '/course-planner'
    | '/dashboard'
    | '/gpa-simulator'
    | '/insights'
    | '/schedule'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/ai-advisor'
    | '/_app/course-planner'
    | '/_app/dashboard'
    | '/_app/gpa-simulator'
    | '/_app/insights'
    | '/_app/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gpa-simulator': {
      id: '/_app/gpa-simulator'
      path: '/gpa-simulator'
      fullPath: '/gpa-simulator'
      preLoaderRoute: typeof AppGpaSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/course-planner': {
      id: '/_app/course-planner'
      path: '/course-planner'
      fullPath: '/course-planner'
      preLoaderRoute: typeof AppCoursePlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-advisor': {
      id: '/_app/ai-advisor'
      path: '/ai-advisor'
      fullPath: '/ai-advisor'
      preLoaderRoute: typeof AppAiAdvisorRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiAdvisorRoute: typeof AppAiAdvisorRoute
  AppCoursePlannerRoute: typeof AppCoursePlannerRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGpaSimulatorRoute: typeof AppGpaSimulatorRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppScheduleRoute: typeof AppScheduleRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAdvisorRoute: AppAiAdvisorRoute,
  AppCoursePlannerRoute: AppCoursePlannerRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGpaSimulatorRoute: AppGpaSimulatorRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppScheduleRoute: AppScheduleRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
