-- ─────────────────────────────────────────────────────────────────────
-- 0008_seed_requirement_link — ~41 req↔req 关系
-- AUTO-GENERATED by scripts/genRequirementAdvice.ts —— DO NOT HAND-EDIT
--
-- 5 档 kind：substitute / prerequisite / excludes / cross_ref / triggers
-- 同 (from, to, kind) ON CONFLICT DO UPDATE（幂等可重跑）
-- ─────────────────────────────────────────────────────────────────────

DO $$
DECLARE
  v_from_id uuid;
  v_to_id uuid;
  v_inserted int := 0;
  v_skipped int := 0;
BEGIN
  -- E2-6 -[substitute]-> C6-1: 劳动 2 学分可由创新创业学分顶 ≤ 2 分
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E2-6' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'C6-1'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'substitute', false, '{"max_credits":2}'::jsonb, '劳动 2 学分可由创新创业学分顶 ≤ 2 分', 'E2-6 cross_ref C6-3')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E2-6', 'C6-1';
  END IF;

  -- E2-8 -[cross_ref]-> E2-6: 通识必修 4 学分 = 劳动 2 + 心理 2
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E2-8' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'E2-6'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'cross_ref', true, '{}'::jsonb, '通识必修 4 学分 = 劳动 2 + 心理 2', 'E2-8')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E2-8', 'E2-6';
  END IF;

  -- E2-8 -[cross_ref]-> E2-7: 通识必修 4 学分 = 劳动 2 + 心理 2
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E2-8' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'E2-7'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'cross_ref', true, '{}'::jsonb, '通识必修 4 学分 = 劳动 2 + 心理 2', 'E2-8')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E2-8', 'E2-7';
  END IF;

  -- E3-1 -[cross_ref]-> E3-2: 通识 8 学分含人类思维与学科史论模块
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E3-1' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'E3-2'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'cross_ref', false, '{}'::jsonb, '通识 8 学分含人类思维与学科史论模块', 'E3-1')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E3-1', 'E3-2';
  END IF;

  -- E3-1 -[cross_ref]-> E3-3: 通识 8 学分含经典阅读模块
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E3-1' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'E3-3'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'cross_ref', false, '{}'::jsonb, '通识 8 学分含经典阅读模块', 'E3-1')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E3-1', 'E3-3';
  END IF;

  -- E3-1 -[cross_ref]-> E3-4: 通识 8 学分含模块课程模块
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E3-1' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'E3-4'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'cross_ref', false, '{}'::jsonb, '通识 8 学分含模块课程模块', 'E3-1')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E3-1', 'E3-4';
  END IF;

  -- E2-6 -[cross_ref]-> C6-1: 劳动教育条款明确引用 C6-3 创新创业学分
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E2-6' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'C6-1'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'cross_ref', true, '{}'::jsonb, '劳动教育条款明确引用 C6-3 创新创业学分', 'E2-6')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E2-6', 'C6-1';
  END IF;

  -- E4-4 -[cross_ref]-> E4-5: 师范生课程结构包含教师教育板块
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E4-4' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'E4-5'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'cross_ref', false, '{}'::jsonb, '师范生课程结构包含教师教育板块', 'E4-4')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E4-4', 'E4-5';
  END IF;

  -- C9-3 -[cross_ref]-> C9-1: 推免综合公式适用范围由 C9-1 资格条款决定
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'C9-3' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'C9-1'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'cross_ref', false, '{}'::jsonb, '推免综合公式适用范围由 C9-1 资格条款决定', 'C9-3')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'C9-3', 'C9-1';
  END IF;

  -- A2-1 -[cross_ref]-> A1-12: 毕业资格审核三档对应毕业/结业/肄业 三档基础条款
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'A2-1' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A1-12'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'cross_ref', true, '{}'::jsonb, '毕业资格审核三档对应毕业/结业/肄业 三档基础条款', 'A2-1')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'A2-1', 'A1-12';
  END IF;

  -- A3-3 -[cross_ref]-> A3-2: 处分期间不可申请学位条款引用学位 GPA 阈值
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'A3-3' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A3-2'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'cross_ref', false, '{}'::jsonb, '处分期间不可申请学位条款引用学位 GPA 阈值', 'A3-3')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'A3-3', 'A3-2';
  END IF;

  -- C2-6 -[cross_ref]-> A3-2: 双学位授予条件引用学位 GPA 阈值（2.0）
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'C2-6' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A3-2'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'cross_ref', false, '{}'::jsonb, '双学位授予条件引用学位 GPA 阈值（2.0）', 'C2-6')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'C2-6', 'A3-2';
  END IF;

  -- C1-9 -[cross_ref]-> A3-2: 辅修学位授予条件引用学位 GPA 阈值
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'C1-9' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A3-2'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'cross_ref', false, '{}'::jsonb, '辅修学位授予条件引用学位 GPA 阈值', 'C1-9')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'C1-9', 'A3-2';
  END IF;

  -- D4-12 -[cross_ref]-> D4-11: 论文重复率结果引用不予答辩 4 触发清单
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'D4-12' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'D4-11'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'cross_ref', false, '{}'::jsonb, '论文重复率结果引用不予答辩 4 触发清单', 'D4-12')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'D4-12', 'D4-11';
  END IF;

  -- B3-1 -[cross_ref]-> A3-2: 学业预警判定引用学位 GPA 阈值
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'B3-1' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A3-2'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'cross_ref', false, '{}'::jsonb, '学业预警判定引用学位 GPA 阈值', 'B3-1')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'B3-1', 'A3-2';
  END IF;

  -- C9-1 -[prerequisite]-> C9-3: 达推免资格才适用综合排名公式
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'C9-1' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'C9-3'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'prerequisite', false, '{}'::jsonb, '达推免资格才适用综合排名公式', 'C9-1')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'C9-1', 'C9-3';
  END IF;

  -- A3-2 -[prerequisite]-> A1-12: 学位 GPA 阈值达成是 '毕业 + 学位' 档前置
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'A3-2' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A1-12'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'prerequisite', false, '{}'::jsonb, '学位 GPA 阈值达成是 ''毕业 + 学位'' 档前置', 'A3-2')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'A3-2', 'A1-12';
  END IF;

  -- E2-1 -[prerequisite]-> A2-1: 思想政治理论课全部通过是毕业资格审核硬要求
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E2-1' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A2-1'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'prerequisite', false, '{}'::jsonb, '思想政治理论课全部通过是毕业资格审核硬要求', 'A2-1')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E2-1', 'A2-1';
  END IF;

  -- E2-2 -[prerequisite]-> A2-1: 大学英语 8 学分完成是毕业资格审核硬要求
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E2-2' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A2-1'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'prerequisite', false, '{}'::jsonb, '大学英语 8 学分完成是毕业资格审核硬要求', 'A2-1')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E2-2', 'A2-1';
  END IF;

  -- E2-4 -[prerequisite]-> A2-1: 公共体育 4 学分完成是毕业资格审核硬要求
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E2-4' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A2-1'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'prerequisite', false, '{}'::jsonb, '公共体育 4 学分完成是毕业资格审核硬要求', 'A2-1')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E2-4', 'A2-1';
  END IF;

  -- E2-5 -[prerequisite]-> A2-1: 国情教育 3 学分完成是毕业资格审核硬要求
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E2-5' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A2-1'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'prerequisite', false, '{}'::jsonb, '国情教育 3 学分完成是毕业资格审核硬要求', 'A2-1')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E2-5', 'A2-1';
  END IF;

  -- E2-6 -[prerequisite]-> A2-1: 劳动教育 2 学分完成是毕业资格审核硬要求
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E2-6' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A2-1'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'prerequisite', false, '{}'::jsonb, '劳动教育 2 学分完成是毕业资格审核硬要求', 'A2-1')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E2-6', 'A2-1';
  END IF;

  -- E2-7 -[prerequisite]-> A2-1: 心理健康 2 学分完成是毕业资格审核硬要求
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E2-7' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A2-1'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'prerequisite', false, '{}'::jsonb, '心理健康 2 学分完成是毕业资格审核硬要求', 'A2-1')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E2-7', 'A2-1';
  END IF;

  -- E3-1 -[prerequisite]-> A2-1: 通识 8 学分完成是毕业资格审核硬要求
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E3-1' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A2-1'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'prerequisite', false, '{}'::jsonb, '通识 8 学分完成是毕业资格审核硬要求', 'A2-1')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E3-1', 'A2-1';
  END IF;

  -- B5-9 -[prerequisite]-> A1-12: 体测达 50 分是 '毕业' 档前置（< 50 按结业/肄业）
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'B5-9' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A1-12'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'prerequisite', false, '{}'::jsonb, '体测达 50 分是 ''毕业'' 档前置（< 50 按结业/肄业）', 'B5-9')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'B5-9', 'A1-12';
  END IF;

  -- E4-4 -[prerequisite]-> E4-5: 师范生需完成 4 板块（含教师教育）才符合培养方案
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E4-4' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'E4-5'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'prerequisite', false, '{}'::jsonb, '师范生需完成 4 板块（含教师教育）才符合培养方案', 'E4-4')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E4-4', 'E4-5';
  END IF;

  -- C1-9 -[prerequisite]-> C2-6: 辅修学位先于双学位审定（双学位需先具备辅修条件）
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'C1-9' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'C2-6'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'prerequisite', false, '{}'::jsonb, '辅修学位先于双学位审定（双学位需先具备辅修条件）', 'C2-6')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'C1-9', 'C2-6';
  END IF;

  -- E4-4 -[excludes]-> E1-3: 师范生培养方案与一般本科 4 大结构互斥（板块分类不同）
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'E4-4' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'E1-3'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'excludes', false, '{}'::jsonb, '师范生培养方案与一般本科 4 大结构互斥（板块分类不同）', 'E4-4')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'E4-4', 'E1-3';
  END IF;

  -- C3-3 -[excludes]-> C9-1: 强基本研衔接转段与普通推免互斥（资格不同）
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'C3-3' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'C9-1'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'excludes', false, '{}'::jsonb, '强基本研衔接转段与普通推免互斥（资格不同）', 'C3-3')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'C3-3', 'C9-1';
  END IF;

  -- A1-10 -[triggers]-> A1-12: 退学情形触发 → 学籍结束 → 肄业档
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'A1-10' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A1-12'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'triggers', false, '{}'::jsonb, '退学情形触发 → 学籍结束 → 肄业档', 'A1-10')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'A1-10', 'A1-12';
  END IF;

  -- A3-3 -[triggers]-> A3-2: 处分期间触发 → 学位申请冻结
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'A3-3' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A3-2'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'triggers', false, '{}'::jsonb, '处分期间触发 → 学位申请冻结', 'A3-3')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'A3-3', 'A3-2';
  END IF;

  -- B3-1 -[triggers]-> B3-4: 学业预警累计 → 第一次退学线 → 试读
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'B3-1' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'B3-4'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'triggers', false, '{}'::jsonb, '学业预警累计 → 第一次退学线 → 试读', 'B3-1')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'B3-1', 'B3-4';
  END IF;

  -- B3-4 -[triggers]-> A1-10: 第一次退学线触发 → 试读（学制内仅限 1 次）
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'B3-4' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A1-10'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'triggers', false, '{}'::jsonb, '第一次退学线触发 → 试读（学制内仅限 1 次）', 'B3-4')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'B3-4', 'A1-10';
  END IF;

  -- B4-4 -[triggers]-> A3-3: 旷课纪律处分触发 → 处分期间学位申请冻结
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'B4-4' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A3-3'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'triggers', false, '{}'::jsonb, '旷课纪律处分触发 → 处分期间学位申请冻结', 'B4-4')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'B4-4', 'A3-3';
  END IF;

  -- B5-9 -[triggers]-> A1-12: 体测 < 50 分触发 → 按结业/肄业档（2023 级起）
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'B5-9' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A1-12'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'triggers', false, '{}'::jsonb, '体测 < 50 分触发 → 按结业/肄业档（2023 级起）', 'B5-9')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'B5-9', 'A1-12';
  END IF;

  -- D4-12 -[triggers]-> D4-11: 论文重复率 30% 整改 / 50% 直接不予答辩
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'D4-12' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'D4-11'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'triggers', false, '{}'::jsonb, '论文重复率 30% 整改 / 50% 直接不予答辩', 'D4-12')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'D4-12', 'D4-11';
  END IF;

  -- D4-11 -[triggers]-> A2-1: 论文不予答辩 → 毕业资格审核失败 → 延期毕业
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'D4-11' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A2-1'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'triggers', false, '{}'::jsonb, '论文不予答辩 → 毕业资格审核失败 → 延期毕业', 'D4-11')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'D4-11', 'A2-1';
  END IF;

  -- C5-2 -[triggers]-> A1-12: 转专业违规处理 → 可能影响毕业档
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'C5-2' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A1-12'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'triggers', false, '{}'::jsonb, '转专业违规处理 → 可能影响毕业档', 'C5-2')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'C5-2', 'A1-12';
  END IF;

  -- C9-3 -[triggers]-> C9-1: 推免综合排名失格 → 推免资格 4 条触发取消
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'C9-3' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'C9-1'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'triggers', false, '{}'::jsonb, '推免综合排名失格 → 推免资格 4 条触发取消', 'C9-3')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'C9-3', 'C9-1';
  END IF;

  -- A4-2 -[triggers]-> A2-1: 学分认定超过 40% 上限 → 毕业资格审核拒绝
  SELECT id INTO v_from_id FROM public.track_requirement WHERE code = 'A4-2' LIMIT 1;
  SELECT id INTO v_to_id   FROM public.track_requirement WHERE code = 'A2-1'   LIMIT 1;
  IF v_from_id IS NOT NULL AND v_to_id IS NOT NULL THEN
    INSERT INTO public.requirement_link (from_req, to_req, kind, bidirectional, metadata, note, source_ref)
    VALUES (v_from_id, v_to_id, 'triggers', false, '{}'::jsonb, '学分认定超过 40% 上限 → 毕业资格审核拒绝', 'A4-2')
    ON CONFLICT (from_req, to_req, kind) DO UPDATE SET
      bidirectional = EXCLUDED.bidirectional,
      metadata = EXCLUDED.metadata,
      note = EXCLUDED.note,
      source_ref = EXCLUDED.source_ref;
    v_inserted := v_inserted + 1;
  ELSE
    v_skipped := v_skipped + 1;
    RAISE NOTICE 'Skipped (req not found): % or %', 'A4-2', 'A2-1';
  END IF;
  RAISE NOTICE 'requirement_link seed done: inserted/updated=%, skipped=%', v_inserted, v_skipped;
END $$;
